# -*- coding: utf-8 -*-
"""netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18NBlk1bFovu99Vuri49vyvcqVjKgcHDL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('mymoviedb.csv', lineterminator='\n')
df.head()

df.info()

df['Genre'].head()

df.duplicated()

df.duplicated().sum()

df.describe()

"""**Requirements:-**
No NaNs or duplicate values.

Release_Date should be converted to datetime and extract only the year.

Overview, Original_Language, and Poster_Url are not useful for analysis.

Outliers are visible in Popularity.

Vote_Average is better categorized.

Genre is comma-separated and needs splitting.
"""

df['Release_Date'] = pd.to_datetime(df['Release_Date'])
print(df['Release_Date'].dtypes)

df['Release_Date'] = df['Release_Date'].dt.year

df.head()

"""Droppings Columns"""

cols = ['Overview', 'Original_Language', 'Poster_Url']
df.drop(cols, axis=1, inplace=True)

df.head()

"""**Categorize Vote_Average**"""

def catigorize_col(df, col, labels):
    edges = [df[col].describe()['min'],
             df[col].describe()['25%'],
             df[col].describe()['50%'],
             df[col].describe()['75%'],
             df[col].describe()['max']]
    df[col] = pd.cut(df[col], edges, labels=labels, duplicates='drop')
    return df

labels = ['not_popular', 'below_avg', 'average', 'popular']
catigorize_col(df, 'Vote_Average', labels)
df['Vote_Average'].unique()

df.head()

df['Vote_Average'].value_counts()

df.dropna(inplace=True)

df.isna().sum()

df.head()

"""**Split and Explode Genre Column
python
Copy code
**
"""

df['Genre'] = df['Genre'].str.split(',')
df = df.explode('Genre').reset_index(drop=True)
df.head()

"""**casting column into category**"""

df['Genre'] = df['Genre'].astype('category')
df['Genre'].dtypes

df.info()

df.nunique()

df.head()

"""**Data Visualization Setup**"""

sns.set_style('whitegrid')

"""Q1 what is the Most Frequent Genre of movies released on netflix"""

df['Genre'].describe()

sns.catplot(y='Genre', data=df, kind='count',
            order=df['Genre'].value_counts().index,
            color='blue')
plt.title('Genre column distribution')
plt.show()

"""Q2- which has highest Vote Average Distribution colimn"""

sns.catplot(y='Vote_Average', data=df, kind='count',
            order=df['Vote_Average'].value_counts().index,
            color='#24854f')
plt.title('Votes distribution')
plt.show()

"""Q3: Most Popular Movie"""

df[df['Popularity'] == df['Popularity'].max()]

"""Q4: Least Popular Movie"""

df[df['Popularity'] == df['Popularity'].min()]

"""Q5: Most Films by Year"""

df['Release_Date'].hist()
plt.title('Release_Date column distribution')
plt.show()

